
<script type="text/javascript">

    try {
        // Referencing a function that does not exist cause an exception
        document.write(sayHello());
        // Since the above line causes an exception, the following line will not be executed
        document.write("This line will not be executed");
    }
    // When an exception occurs, the control is transferred to the catch block
    catch (e) {
        document.write("Description = " + e.description + "<br/>");
        document.write("Message = " + e.message + "<br/>");
        document.write("Stack = " + e.stack + "<br/><br/>");
    }
    finally {
        document.write("This line is guaranteed to execute");
    }

    function divide() {
        var numerator = Number(prompt("Enter numerator"));
        var denominator = Number(prompt("Enter denominator"));

        try {
            if (denominator == 0) {
                throw {
                    error: "Divide by zero error",
                    message: "Denominator cannot be zero"
                };
            }
            else {
                alert("Result = " + (numerator / denominator));
            }
        }
        catch (e) {
            document.write(e.error + "<br/>");
            document.write(e.message + "<br/>");
        }
    }

    divide();

</script>